{% set version = "0.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set cran_mirror = 'https://cran.r-project.org' %}

package:
  name: r-ggplotify
  version: {{ version|replace("-", "_") }}

source:
  fn: ggplotify_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggplotify_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggplotify/ggplotify_{{ version }}.tar.gz
  sha256: 7e7953a2933aa7127a0bac54375e3e0219a0744cfc3249c3d7b76065f7a51892

build:
  noarch: generic
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-ggplot2
    - r-gridgraphics
    - r-rvcheck
  run:
    - r-base
    - r-ggplot2
    - r-gridgraphics
    - r-rvcheck

test:
  commands:
    - $R -e "library('ggplotify')"           # [not win]
    - "\"%R%\" -e \"library('ggplotify')\""  # [win]

about:
  home: https://github.com/GuangchuangYu/ggplotify
  license: Artistic-2.0
  summary: Convert plot function call (using expression or formula) to 'grob' or 'ggplot' object
    that compatible to the 'grid' and 'ggplot2' ecosystem. With this package, we are
    able to e.g. using 'cowplot' to align plots produced by 'base' graphics, 'grid',
    'lattice', 'vcd' etc. by converting them to 'ggplot' objects.
  license_family: OTHER

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
