{% set version = "0.0.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggplotify
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggplotify_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggplotify/ggplotify_{{ version }}.tar.gz
  sha256: 1052b6e4bcd2b933193d6ddf8281767aa10ccf3849ff4972cf5aef18d273a2ef

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-gridgraphics
    - r-rvcheck
  run:
    - r-base
    - r-ggplot2
    - r-gridgraphics
    - r-rvcheck

test:
  commands:
    - $R -e "library('ggplotify')"           # [not win]
    - "\"%R%\" -e \"library('ggplotify')\""  # [win]

about:
  home: https://github.com/GuangchuangYu/ggplotify
  license: Artistic-2.0
  summary: Convert plot function call (using expression or formula) to 'grob' or 'ggplot' object that compatible to the 'grid' and 'ggplot2' ecosystem. With this package, we are able to e.g. using 'cowplot' to align plots produced by 'base' graphics, 'grid', 'lattice', 'vcd' etc. by converting them to 'ggplot' objects.
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
