# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "pPH0UgMaUgBvRgRrqMjYhJSyqbweAUPyOApY4n/h7oA3665dF5gDlGc+SamNUsL7fYZx/Xd7whtgF/T+l2Cx17vqd4j6Ap7brMaTzxYRBgjjJT0Tzatkwi0BdDh7bYdxO9JyyrrriSnLdQ4du8OMGl1CyLsw+WCrH3CyR3ddFoM8McqmDSsnwNSkyXkS/5COVJbntUnx7A2HBjwM6psA5hi0f9NWX8x3t1sdj6aOFspF3W2MrMUp44eirWAQHW5byNH5c5gGvzxX0lGDoFFm44OnaENQ1NBCLmFMPJJ+uHkY4+36tLSB33oSPHlrorA1CGmm5pYOFKp6w0OnJ4ml+esrQkmX4iw4lA9Bq/7dXU8mPpdXqVe6b9QyNXLlAsbXN97Syrk4F7x480b2B3W2tjbF8oWHpVwVQtAm8jxYkwvBv0wF/T9zjx8wGnUDNXXKVbwbjlJaFw7YaKtjg+jjXbEJjogiykLk/vWiMPjmgiJQ8j6V60a30Bp29gGDfkoO7xz2lZCEw7r9L+ek3dGheNt0uzHHLY/Ln9a6z4/LUyHTca/xH0lP77sdXS6Nvs++ZNO+HlHXgMH6sZ++gnNy0B/RhgBkUQ3XJR9GUNr+Wj5WVlmox/190ZVfAoKPSx8QvyIhliPgSRVJcP3cglKw+cwK/ClpDRl3hhHnxu+Clcg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
