travis:
  secure:
    BINSTAR_TOKEN: Xt4y2CBGH37iWXXeC5MZY4IObXqzomA0C8y+hnxSJT7C5G561egZHrSKUslzvX3GwscE2VXo5V7EZX1OT/CYus0mSNyRXejWZacixSm5gK67MNQx53GXyQEyGdVbIA/MUMicJyhQRZYOvV93aYiF1GwQCGEAZO3+hDhCjqLFcgcl8Do1jqVF39bXp5KrAUTO0ctdFxoJfVHbdYevvbUXPOtYPSTeaF3Xo/wL95RYV+/wgnUaA6P6fQt/Kwd2oD5krM8lo2kNZtW7NwxjjiOqBOXZzPc3GsR91UFP/eIzpRuWGniDXIO/SO5rhdO+SS3DnYiHAAlVHdN6997Vd9mCcYwp/mSzFn6RNUAI9a2QyRHGO8MyjqMGDzlzXxZQTLNsQEsRt/6YbC935TTe2P4t5SuFwz9K2Jyk1/tXNA1ymd5GqfJB/yUZALT0vWOiezLEFFihvFYTRcSL2iW9HIFr+fHFKYQq1vYkeF6eNY0eOpu6gJD52/w5FR5vaN9twO0K7j0NME4rLuLj+2349dcYlGVSyoQSJdXPiadbMMNxvtJMIOkS7QG+vO4OqVNhjfDF30cnt9dvzU9xX2dawTkwGzsxMv4fag0N6f3ZPojodBzZhtT25LjlB+VOo1B52yTEHPzDbgPP6Kz6xAP3tojA2bIwiNFl2V6xjDcuqDQNcgk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
