travis:
  secure:
    BINSTAR_TOKEN: ZXbZGjeifyFYev13+s66mqQuU233rKlavKfoTBNaY7t8OitEo8EvFek9sBhGHRp2YLL8qTaZ6qKIhkzB8qLjwJGnmkv4Dkeb9bbjW5TA4CUI8BG5gAluMrAIaW6JiBeVOtyWAKzDU8APZIlVisLRxH2CMbQwEEDVmq0aUZgiqIKifxFxV5E0mQoX2bqj/sgQ8SaEi71fogZVNmnC6f2HgsYrqJWXDiINDB/SEciuqAx4XltgxJ/kG0TIbMeoAV9Rr9cchMYTDZOa0qmywgjlNwEWZsKHocjSxq8+Ns5PUIJ1slo5c2rMe62XelRdh4o+3ZBbIsptDdEpTW9VvwKO9HQ1alBDsBi5e//3s2RY1UHgu8WuXoZQGjaG34yh+RMrNRs2+sU2q3/zUx4RLED87tX1UrIkmb6AMKVb6O0NenpNjjOv98i1zb844vPMuIuGIf63/Xi62zTFuFu3vAdx8NJ7LrOL0+TItA1wSnJ/xTPjp16UeTm9WTm6k5QLB51cnZRUOOYWJ8MQuT2wL/zB5F0p9HIpacqcANoJ4c88j7jC4F9vIODBUzUE8zXznoL33UmmfyEz0DsmgsVznQdi2w6LXUmvLfFK6V8TZefrj1NjtHAn6wB1ZbAkcuthVD+eQrOte2SwkXh3TlTEEvadDtpsJgxHWhCxBuUrBI5HdDE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
