appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pPH0UgMaUgBvRgRrqMjYhJSyqbweAUPyOApY4n/h7oA3665dF5gDlGc+SamNUsL7fYZx/Xd7whtgF/T+l2Cx17vqd4j6Ap7brMaTzxYRBgjjJT0Tzatkwi0BdDh7bYdxO9JyyrrriSnLdQ4du8OMGl1CyLsw+WCrH3CyR3ddFoM8McqmDSsnwNSkyXkS/5COVJbntUnx7A2HBjwM6psA5hi0f9NWX8x3t1sdj6aOFspF3W2MrMUp44eirWAQHW5byNH5c5gGvzxX0lGDoFFm44OnaENQ1NBCLmFMPJJ+uHkY4+36tLSB33oSPHlrorA1CGmm5pYOFKp6w0OnJ4ml+esrQkmX4iw4lA9Bq/7dXU8mPpdXqVe6b9QyNXLlAsbXN97Syrk4F7x480b2B3W2tjbF8oWHpVwVQtAm8jxYkwvBv0wF/T9zjx8wGnUDNXXKVbwbjlJaFw7YaKtjg+jjXbEJjogiykLk/vWiMPjmgiJQ8j6V60a30Bp29gGDfkoO7xz2lZCEw7r9L+ek3dGheNt0uzHHLY/Ln9a6z4/LUyHTca/xH0lP77sdXS6Nvs++ZNO+HlHXgMH6sZ++gnNy0B/RhgBkUQ3XJR9GUNr+Wj5WVlmox/190ZVfAoKPSx8QvyIhliPgSRVJcP3cglKw+cwK/ClpDRl3hhHnxu+Clcg=}
